spring:
  application:
    name: kcs
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:geeshow
    #    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        format_sql: true
logging.level:
  org.hibernate.SQL: info
#  org.hibernate.SQL: debug

server:
  port: 8080

kcs:
  data:
    load-enabled: true
    path: "classpath:data/*.csv"
    charset: EUC-KR
